version: '3'
services:
  db:
    image: postgres
    container_name: postgres_k8s
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: domino
    ports:
      - '5432:5432'

  app:
    image: djagoda881/cat-facts
    container_name: app_1
    environment:
      - POSTGRES_HOST=postgres_k8s
